# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

target "MusicShare" do

pod "RNBlurredSideViewController"
pod "iOS-blur"
pod "FXBlurView"


end

target "MusicShareTests" do

end

